 name : Behave project tests

 on:
   push:
     branches:
       - master

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./features/

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          Python-version:${{ matrix.python-version }}


      - name: Installing AWS Cli
        shell: bash
        run: |
          sudo apt update
          sudo apt install awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Installing the packages
        run: pip install -r requirements.txt
      - name: Running behave test
        run: behave
      - run: echo "Job completed."